import type { SignalEventV1, SignalGa4FieldMapV1, SignalWarehouseRowV1 } from './types.js';
import { SIGNAL_EVENT_VERSION, SIGNAL_GA4_EVENT_NAME } from './types.js';

export const SIGNAL_GA4_FIELD_MAP_V1: SignalGa4FieldMapV1 = {
  eventName: SIGNAL_GA4_EVENT_NAME,
  fields: {
    v: 'v',
    event_id: 'event_id',
    ts: 'ts',
    host: 'host',
    url: 'url',
    ref: 'ref',
    net_tier: 'net_tier',
    net_tcp_ms: 'net_tcp_ms',
    net_tcp_source: 'net_tcp_source',
    device_tier: 'device_tier',
    device_cores: 'device_cores',
    device_memory_gb: 'device_memory_gb',
    device_screen_w: 'device_screen_w',
    device_screen_h: 'device_screen_h',
    lcp_ms: 'lcp_ms',
    cls: 'cls',
    inp_ms: 'inp_ms',
    fcp_ms: 'fcp_ms',
    ttfb_ms: 'ttfb_ms',
    effective_type: 'effective_type',
    downlink_mbps: 'downlink_mbps',
    rtt_ms: 'rtt_ms',
    save_data: 'save_data',
    connection_type: 'connection_type',
    pkg_version: 'pkg_version',
    browser: 'browser',
    nav_type: 'nav_type',
    navigation_type: 'navigation_type',
    lcp_load_state: 'lcp_load_state',
    lcp_element_type: 'lcp_element_type',
    inp_load_state: 'inp_load_state',
    interaction_type: 'interaction_type',
    input_delay_ms: 'input_delay_ms',
    processing_duration_ms: 'processing_duration_ms',
    presentation_delay_ms: 'presentation_delay_ms'
  }
};

export function flattenSignalEventForGa4(event: SignalEventV1): Record<string, string | number | boolean | null> {
  return {
    event: SIGNAL_GA4_EVENT_NAME,
    v: event.v,
    event_id: event.event_id,
    ts: event.ts,
    host: event.host,
    url: event.url,
    ref: event.ref,
    net_tier: event.net_tier,
    net_tcp_ms: event.net_tcp_ms,
    net_tcp_source: event.net_tcp_source,
    device_tier: event.device_tier,
    device_cores: event.device_cores,
    device_memory_gb: event.device_memory_gb,
    device_screen_w: event.device_screen_w,
    device_screen_h: event.device_screen_h,
    lcp_ms: event.vitals.lcp_ms,
    cls: event.vitals.cls,
    inp_ms: event.vitals.inp_ms,
    fcp_ms: event.vitals.fcp_ms,
    ttfb_ms: event.vitals.ttfb_ms,
    effective_type: event.context.effective_type,
    downlink_mbps: event.context.downlink_mbps,
    rtt_ms: event.context.rtt_ms,
    save_data: event.context.save_data,
    connection_type: event.context.connection_type,
    pkg_version: event.meta.pkg_version,
    browser: event.meta.browser,
    nav_type: event.meta.nav_type,
    navigation_type: event.meta.navigation_type ?? null,
    lcp_load_state: event.vitals.lcp_attribution?.load_state ?? null,
    lcp_element_type: event.vitals.lcp_attribution?.element_type ?? null,
    inp_load_state: event.vitals.inp_attribution?.load_state ?? null,
    interaction_type: event.vitals.inp_attribution?.interaction_type ?? null,
    input_delay_ms: event.vitals.inp_attribution?.input_delay_ms ?? null,
    processing_duration_ms: event.vitals.inp_attribution?.processing_duration_ms ?? null,
    presentation_delay_ms: event.vitals.inp_attribution?.presentation_delay_ms ?? null
  };
}

export function toSignalWarehouseRow(event: SignalEventV1): SignalWarehouseRowV1 {
  return {
    schema_version: SIGNAL_EVENT_VERSION,
    event_id: event.event_id,
    observed_at: new Date(event.ts).toISOString(),
    host: event.host,
    path: event.url,
    referrer: event.ref,
    net_tier: event.net_tier,
    net_tcp_ms: event.net_tcp_ms,
    net_tcp_source: event.net_tcp_source,
    device_tier: event.device_tier,
    device_cores: event.device_cores,
    device_memory_gb: event.device_memory_gb,
    device_screen_w: event.device_screen_w,
    device_screen_h: event.device_screen_h,
    lcp_ms: event.vitals.lcp_ms,
    cls: event.vitals.cls,
    inp_ms: event.vitals.inp_ms,
    fcp_ms: event.vitals.fcp_ms,
    ttfb_ms: event.vitals.ttfb_ms,
    effective_type: event.context.effective_type,
    downlink_mbps: event.context.downlink_mbps,
    rtt_ms: event.context.rtt_ms,
    save_data: event.context.save_data,
    connection_type: event.context.connection_type,
    browser: event.meta.browser,
    nav_type: event.meta.nav_type,
    navigation_type: event.meta.navigation_type ?? null,
    lcp_load_state: event.vitals.lcp_attribution?.load_state ?? null,
    lcp_target: event.vitals.lcp_attribution?.target ?? null,
    lcp_element_type: event.vitals.lcp_attribution?.element_type ?? null,
    lcp_resource_url: event.vitals.lcp_attribution?.resource_url ?? null,
    inp_load_state: event.vitals.inp_attribution?.load_state ?? null,
    interaction_target: event.vitals.inp_attribution?.interaction_target ?? null,
    interaction_type: event.vitals.inp_attribution?.interaction_type ?? null,
    interaction_time_ms: event.vitals.inp_attribution?.interaction_time_ms ?? null,
    input_delay_ms: event.vitals.inp_attribution?.input_delay_ms ?? null,
    processing_duration_ms: event.vitals.inp_attribution?.processing_duration_ms ?? null,
    presentation_delay_ms: event.vitals.inp_attribution?.presentation_delay_ms ?? null
  };
}
